version: "3.8"

services:
  backend:
    image: sauvikxdocker/task-backend:latest
    container_name: task-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://worksauvikchatterjee:v7ianBiOqYWT8ygD@my-cluster.fqy69.mongodb.net/?retryWrites=true&w=majority&appName=My-Cluster
    restart: always

  frontend:
    image: sauvikxdocker/task-frontend:latest
    container_name: task-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
