name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: 13.201.74.124
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          envs: BACKEND_ENV
          script: |
            rm -rf Notes-Full-Stack
            git clone https://github.com/sauvikchatterjee07/Notes-Full-Stack.git
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 22.13.1

            cd Notes-Full-Stack/Frontend/Task-App-Frontend
            npm install
            npm run build

            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo cp -r dist/* /var/www/html/

            cd ../../Backend
            echo "$BACKEND_ENV" > .env
            npm install
            npm install -g pm2
            pm2 stop notes-backend || true
            pm2 start index.js --name notes-backend -f
