name: CI/CD Pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/task-backend:latest ./Backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/task-frontend:latest ./Frontend/Task-App-Frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-frontend:latest

      - name: SSH into EC2 and deploy using Docker Compose
        uses: appleboy/ssh-action@v1
        with:
          host: 13.203.231.112
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Update docker and docker-compose if not installed
            sudo apt update
            sudo apt install -y docker.io docker-compose

            # Ensure user has docker permissions
            sudo usermod -aG docker ubuntu

            # Pull latest code
            rm -rf Notes-Full-Stack || true
            git clone https://github.com/sauvikchatterjee07/Notes-Full-Stack.git

            cd Notes-Full-Stack

            # Pull latest images from Docker Hub
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/task-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/task-frontend:latest

            # Use existing docker-compose.yml from repo
            docker-compose down
            docker-compose up -d
