on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout the code to github own server
        uses: actions/checkout@v2

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: 13.232.41.125
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            rm -rf Notes-Full-Stack
            git clone https://github.com/sauvikchatterjee07/Notes-Full-Stack.git

            # Install Node.js and npm
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v

            cd Notes-Full-Stack/Frontend/Task-App-Frontend
            npm install
            npm run build

            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo mkdir -p /var/www/html
            sudo cp -r dist/* /var/www/html/

            cd ../../Backend
            echo "${{ secrets.BACKEND_ENV }}"
            printf "%s\n" "${{ secrets.BACKEND_ENV }}" > .env
            cat .env
            npm install
            sudo npm install -g pm2
            pm2 stop notes-backend || true
            pm2 start index.js --name notes-backend -f
