on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout the code to GitHub's runner
        uses: actions/checkout@v2

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: 65.0.108.59
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            # Clean previous deployment if any
            rm -rf Notes-Full-Stack

            # Clone the latest code
            git clone https://github.com/sauvikchatterjee07/Notes-Full-Stack.git

            # Install Node.js and npm
            curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
            sudo apt-get install -y nodejs
            node -v
            npm -v

            # Build the frontend
            cd Notes-Full-Stack/Frontend/Task-App-Frontend
            npm install
            npm run build

            # Setup and start nginx
            sudo apt update
            sudo apt install -y nginx
            sudo systemctl start nginx
            sudo systemctl enable nginx
            sudo mkdir -p /var/www/html
            sudo cp -r dist/* /var/www/html/

            # Setup the backend
            cd ../../Backend

            # Create .env file with secrets (no indentation!)
            cat <<EOF > .env
PORT=${{ secrets.PORT }}
MONGO_URI=${{ secrets.MONGO_URI }}
EOF

            # Print the .env file for debugging (optional)
            cat .env

            # Install dependencies and start backend
            npm install
            sudo npm install -g pm2
            pm2 stop notes-backend || true
            pm2 start index.js --name notes-backend -f
