name: Test EC2 SSH Connection

on:
    push:
        branches:
            - main

jobs:
    test-ssh:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup SSH key and agent
              run: |
                  # Save the private key from the GitHub secrets
                  echo "${{ secrets.EC2_KEY }}" > key.pem
                  chmod 600 key.pem
                  eval $(ssh-agent -s)
                  ssh-add key.pem

            - name: Test SSH Connection to EC2
              run: |
                  # SSH into the EC2 instance
                  ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful!'"
