name: Deploy Notes Full Stack App

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: SSH and Deploy to EC2
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_KEY }}
                  script: |
                      # Navigate to the project directory
                      cd ~/Notes-Full-Stack

                      # Pull latest changes
                      git pull origin main

                      # Backend setup
                      cd Backend
                      npm install
                      pm2 restart notes-backend

                      # Frontend setup
                      cd ../Frontend/Task-App-Frontend
                      npm install
                      npm run build

                      # Deploy frontend build
                      sudo cp -r dist/* /var/www/html/
