name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/Notes-Full-Stack
          
          # Pull latest changes
          git pull origin main

          # Backend
          cd Backend
          npm install
          pm2 restart notes-backend

          # Frontend
          cd ../Frontend/Task-App-Frontend
          npm install
          npm run build
          sudo cp -r dist/* /var/www/html/
        EOF
