on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code to github own server
        uses: actions/checkout@v2

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1
        with:
          host: 13.203.227.138
          username: ubuntu
          key: ${{ secrets.EC2_KEY}}
          port: 22
          script: |
          ls
          whoami
